### ISSUE TITLE
Javascript not registering Events

### ISSUE THREAD

**Issue by skukx** [solidusio-contrib/solidus_product_assembly#23]
Started with Fresh install of solidus `v2.4`
In the gemfile:
```ruby
gem 'solidus_product_assembly', github: 'solidusio-contrib/solidus_product_assembly'
```

To Recreate:
- Go To Admin
- Go to a completed order
- Go to the `deliveries` tab of the order details
- Click on any of the buttons in the shipment manifest to perform an action
- Nothing happens

![image](https://user-images.githubusercontent.com/1091314/35070410-0f5b56e0-fb92-11e7-817f-9aa71721f16b.png)

This is most likely due to the `Deface` override which replaces that view.
https://github.com/solidusio-contrib/solidus_product_assembly/blob/master/app/overrides/spree/admin/orders/_shipment/stock_contents.html.erb.deface

**Comment by kennyadsl** [comment]
This should be fixed by the lastly merged/opened PRs right?

**Comment by spaghetticode** [comment]
The `edit` button is still not working. I'm taking care of this.

**Comment by spaghetticode** [comment]
The `edit` button does not exist on Solidus >=2.3, so I think we can safely remove it. @kennyadsl what do you think? 

It was removed from Solidus `_shipment_manifest.html.erb` with commit [b252e9adcd02b5b0f0f89cdcfae583e72ae12fb7](https://github.com/solidusio/solidus/commit/b252e9adcd02b5b0f0f89cdcfae583e72ae12fb7)

**Comment by aitbw** [comment]
Closed via #34
